name: CI/CD Pipeline

on:
  pull_request:
    branches:
      - main  # Substitua 'main' pelo nome da sua branch principal, se for diferente

jobs:
  RunTest:
    runs-on: windows-2022

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Instalar Java 8
        uses: actions/setup-java@v2
        with:
          java-version: "8"
          cache: maven

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Installar chrome
        uses: nanasess/setup-chromedriver@v2

      - name: Start Chromedriver
        run: chromedriver --url-base=/wd/hub &

      - name: Run Test
        run: mvn test -Dtest=RunCucumber -Dbrowser=chrome-ci cluecumber-report:reporting

