name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Substitua 'main' pelo nome da sua branch principal, se for diferente

jobs:
  RunTest:
    runs-on: windows-2022

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Instalar Java 11
        uses: actions/setup-java@v2
        with:
          java-version: "11"
          distributon: "adopt"
          cache: maven

      - name:
      - uses: actions/checkout@v2

      - uses: nanasess/setup-chromedriver@v2
      - run: chromedriver --url-base=/wd/hub &

      - name: Run Test
        run:   mvn test -Dtest=RunCucumber -Dbrowser=chrome-ci cluecumber-report:reporting






      # Adicione mais etapas conforme necessário, como construção do aplicativo e implantação
